//! Modal subsystem: the [`Modal`] trait, the [`ModalStack`] the App dispatches through,
//! and one adapter per modal under `src/app/modal/`.

pub mod chrome;
pub(crate) mod docs_link;
pub mod stack;
pub mod types;

pub mod about;
pub mod command_palette;
pub mod config_warning;
pub mod daily_tip;
pub mod diff_bulk_confirm;
pub mod diff_intro;
pub mod diff_quit_confirm;
pub mod diff_resolve_confirm;
pub mod dirty_conflict;
pub mod dirty_conflict_discard_confirm;
pub mod dirty_conflict_save_copy;
pub mod dirty_guard;
pub mod export;
pub mod export_success;
pub mod export_theme;
pub mod figures_enabled;
pub mod file_deleted;
pub mod images_enabled;
pub mod insert_table;
pub mod keybinds;
pub mod markdown_cheat_sheet;
pub mod notice;
pub mod overwrite_confirm;
pub mod paste_image;
pub mod post_upgrade;
pub mod quit_confirm;
pub mod remote_image;
pub mod save_as;
pub mod search_replace;
pub mod section_picker;
pub mod settings;
pub mod terminal_capabilities;
pub mod theme_downgrade;
pub mod theme_picker;
pub mod tips_index;
pub mod update;
pub mod welcome;
pub mod width_injection;

pub use stack::ModalStack;
#[allow(unused_imports)]
pub use types::ModalKind;
pub use types::{Modal, ModalOutcome, ModalRenderCtx};

pub use about::AboutModal;
pub use command_palette::CommandPaletteModal;
pub use config_warning::ConfigWarningModal;
pub use daily_tip::DailyTipModal;
pub use diff_bulk_confirm::DiffBulkConfirmModal;
pub use diff_intro::DiffIntroModal;
pub use diff_quit_confirm::DiffQuitConfirmModal;
pub use diff_resolve_confirm::DiffResolveConfirmModal;
pub use dirty_conflict::DirtyConflictModal;
pub use dirty_guard::DirtyGuardModal;
pub use export_success::ExportSuccessModal;
pub use figures_enabled::FiguresEnabledPromptModal;
pub use file_deleted::FileDeletedModal;
pub use images_enabled::ImagesEnabledPromptModal;
pub use insert_table::InsertTableModal;
pub use keybinds::KeybindsOverlayModal;
pub use markdown_cheat_sheet::CheatSheetModal;
pub use notice::NoticeModal;
pub use overwrite_confirm::OverwriteConfirmModal;
pub use paste_image::{ClipboardReadModal, PasteImageModal};
pub use post_upgrade::PostUpgradeModal;
pub use quit_confirm::QuitConfirmModal;
pub use remote_image::RemoteImagePromptModal;
pub use save_as::SaveAsModal;
pub use search_replace::SearchReplaceModal;
pub use section_picker::SectionPickerModal;
pub use settings::SettingsOverlayModal;
pub use terminal_capabilities::TerminalCapabilitiesModal;
pub use theme_downgrade::ThemeDowngradeModal;
pub use theme_picker::ThemePickerModal;
pub use tips_index::TipsIndexModal;
pub use update::UpdateModal;
pub use welcome::WelcomeModal;
pub use width_injection::WidthInjectionWarning;
